Close panels
KSU-CS-Software-Engineering/VetMedSim pull request #13
Opened 2019-04-13 16:03 UTC by jaredvincent

This PR updates the Panel prefab to allow the close button to actually function.  Doing so required the addition of a script to toggle a gameobject's active state, as well as a script to listen to allow buttons to listen to gestures and trigger onClick events when appropriate.

2019-04-14 14:05 UTC, ashley23mo approved these changes

2019-04-14 16:15 UTC, myangmi approved these changes

2019-04-14 16:23 UTC, Trosclair requested changes
public void EnableObject()
        {
            gameObject.SetActive(true);
        }

        /// <summary>
        /// Deactivates attached object
        /// </summary>
        public void DisableObject()
        {
            gameObject.SetActive(false);
        }
need to have space before/after true/false in the SetActive call

2019-04-15 17:05 UTC, Trosclair approved these changes

2019-04-15 18:15 UTC, myangmi approved these changes

2019-04-16 21:05 UTC, merged