Clinic layout
KSU-CS-Software-Engineering/VetMedSim pull request #3
Opened 2018-11-20 22:47 UTC by jaredvincent

I-04 Layout-Architecture

Epic 72: [New Layout](https://dev.azure.com/asmorton0054/VetSim/_workitems/edit/72/)

Clinic scene based on feedback from client at the conclusion of sprint 3.  Scene includes tilemaps for floors and ground, walls, and wall tops as well as prefabs for scene furniture objects including colliders.

2018-11-21 00:46 UTC, ksu-shanemat requested changes
The version of the project mismatches the newest version of Unity. This would not be much of an issue, except Unity crashes (see attached screenshot) every time I try to open it with version 2018.2.16f1 :// 

![image](https://user-images.githubusercontent.com/42660075/48811712-99b8ca80-ecf4-11e8-9836-6fcf1e26a03c.png)

EDIT: My bad, did not have checked out the most current version, sorry O:))

2018-11-21 00:50 UTC, ksu-shanemat approved these changes

2018-11-21 01:15 UTC, ksu-shanemat requested changes
Please update the project version to match the newest one (2018.2.16f1).
Some prefabs are missing colliders (deskVertical, stand1, vendingMachine1)

2018-11-21 03:31 UTC, ksu-shanemat approved these changes

2018-11-24 04:04 UTC, ashley23mo approved these changes
Looks good to me.
Mat- If we're adding Payton already, should I go ahead and add Michael?

2018-11-25 03:10 UTC, merged